# spring:
#   application:
#     name: food-ordering-system
  
#   datasource:
#     url: jdbc:mysql://localhost:3306/food_ordering_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     username: root
#     password: macos2024
#     driver-class-name: com.mysql.cj.jdbc.Driver
  
#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL8Dialect
#         format_sql: true
  
#   flyway:
#     enabled: true
#     locations: classpath:db/migration
#     baseline-on-migrate: true
  
#   thymeleaf:
#     cache: false
#     prefix: classpath:/templates/
#     suffix: .html
  
#   security:
#     user:
#       name: admin
#       password: admin123
#       roles: ADMIN

# server:
#   port: 8080

# logging:
#   level:
#     org.springframework.security: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  application:
    name: food-ordering-system


  datasource:
    # Use Railway-provided env vars if they exist, otherwise fallback to local dev
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:food_ordering_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:macos2024}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # url: jdbc:mysql://root:AnDPjCBkeFgthSpmGVCtHYBUAtUSwJbF@interchange.proxy.rlwy.net:58715/railway
    # username: root
    # password: AnDPjCBkeFgthSpmGVCtHYBUAtUSwJbF
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  mvc:
    servlet:
      path: /
    async:
      request-timeout: 30000

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: ${PORT:8080}
  tomcat:
    max-connections: 8192
    accept-count: 100
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
  http2:
    enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
